### ISSUE TITLE
Desktop application on localhost:3000? 

### ISSUE THREAD

**Issue by nicobo** [linuxserver/docker-digikam#13]
Hi

This is very interesting to have digikam on docker, but AFAIK its a desktop app and the doc says it's as available on localhost:3000?
The doc should explain how it works and what this image delivers  regarding the desktop app digikam.

**Comment by AlmightyFrog** [comment]
I do not get your point, but maybe following helps you:

Yes, digikam is a desktop app, the purpose of this image is to run it inside an remote desktop which you can access via browser anywhere.
Just make the app fullscreen and it is a really nice experience except video (see #9).

**Comment by nicobo** [comment]
OK so it's more a way to have it installed in a "standard" docker way on a remote desktop. Maybe   useful when the disk containing photos is attached to this distant machine...

Thanks, I didn't get it at first because I'm more used to headless images.
Still that may need a bit of an introduction in the readme.

**Comment by aptalca** [comment]
It is a headless image. It makes digikam interface available via a web browser as described in the readme.

It doesn't have to be on a "distant" machine.

**Comment by nicobo** [comment]
@aptalca of course it doesn't have to be distant, but then what's the use of accessing it via a web browser since you have local access to the machine and a display, obviously ?
I thought I got it with @AlmightyFrog answer but your comment makes me wonder...?

I don't want to troll I'm just curious...

**Comment by aptalca** [comment]
The same arguments for why people run apps in containers instead of installing stuff on bare metal also apply here.
