### ISSUE TITLE
Non-English characters problem

### ISSUE THREAD

**Issue by sse450** [linuxserver/docker-digikam#16]
I can't use non-english characters in filenames.

How can I force the docker to use UTF-8? Tried to pass "en_US.UTF-8" in LANG, LANGUAGE and LC_ALL variables with no cure.

I would appreciate any hint.

**Comment by thelamer** [comment]
Please use the "KEYBOARD" env variable to use a non english layout, see here for available layouts:
https://github.com/linuxserver/gclient#keyboard-layouts
