### ISSUE TITLE
Migrate r-pufky/digikam + users to linuxserver.io/digikam

### ISSUE THREAD

**Issue by r-pufky** [linuxserver/docker-digikam#17]
## Desired Behavior
I've stopped using docker for containers for about two years now, but still support my digikam (100k+ ~400k internally ) and steam (10k+ ~90k) images.

I'd like to discuss migrating existing digikam user install base to the linuxserver.io/digikam image, with feature parity & minimal migration impacts.

## Current Behavior
See repository here: https://github.com/r-pufky/digikam currently, I think there are a few things to touch on:

* sqlite, postgres, mysql/maria db backend support in the LS image
* VNC direct connections
* CJK_FONT - Asian character support (required in case pre-existing users have glyphs in current data)
* locale setting. Default is UTF-8, but users could set anything.
* User specific reported bugfixes. Mostly library additions to the base image to enable certain support (e.g. for facial recognition support, there are certain DB backend requirements for it to work). See: https://github.com/r-pufky/digikam/issues?q=is%3Aissue+is%3Aclosed

## Alternatives Considered
Let me know what you think. This is just a discussion starter to see what your thoughts are and potential ways forward while minimizing any user interruption.

**Comment by thelamer** [comment]
Our gui baseimage actually uses xrdp and guacamole. The actual rendering of Chinese characters is possible but the user would not be able to type them in https://github.com/linuxserver/gclient#keyboard-layouts , this is a guacamole limitation at the time, it cannot translate the keypresses into the correct x11 codes for xrdp currently. Also VNC connections would not be possible but rdp on 3389 would be.

**Comment by r-pufky** [comment]
> Our gui baseimage actually uses xrdp and guacamole. The actual rendering of Chinese characters is possible but the user would not be able to type them in https://github.com/linuxserver/gclient#keyboard-layouts , this is a guacamole limitation at the time, it cannot translate the keypresses into the correct x11 codes for xrdp currently.

Do you know if unicode control characters are supported from the interface (e.g. for å - windows: alt+0229 linux: ctrl+shift+0229)?

>  Also VNC connections would not be possible but rdp on 3389 would be.

My image was primarily designed to serve digikam through a webface, with VNC being a optional feature to use because of the base image. I think VNC vs. RDP is not a hard requirement in that regard.

**Comment by thelamer** [comment]
It's not an issue with control characters it's the code lacking the ability to use the characters properly. Instead of keydown concept where you send a literal key the input from the browser is translated directly into x11 keycodes. From there the guacd server sends those keycodes to xrdp, both guacd and xrdp need to know what the keyboard layout is for the characters to land on the remote desktop. Right now that list of keyboard layouts is all that is supported. You can set a keymap image level (in Linux) and if the user uses an English qwerty on the machine they are accessing from it will work, but in general I can't imagine when this would be applicable.
Long answer is it is mostly Europe and NA support, RU and Asia is missing until someone takes the time to map out support. https://github.com/apache/guacamole-server/tree/master/src/protocols/rdp/keymaps

In general out gui baseimage uses RDP because of the performance, sound support, and pixel perfect rendering. It's a better overall experience especially full screen. Localization is definitely in the con column.

**Comment by thelamer** [comment]
@r-pufky did you want this still open? I went through the issues and things you mentioned and added everything we could. But universal localization is a no go. 

As far as kitchen sink style for support stuff like firefox could be installed, but in general Arch is pretty good about depends: 
https://archlinux.org/packages/extra/x86_64/digikam/

Is anything missing here? https://github.com/linuxserver/docker-digikam/blob/master/package_versions.txt they have a pretty heavy depends tree.

**Comment by r-pufky** [comment]
Heya, thanks for the ping; I haven't had a good block of time to
specifically dig into this. I'm going to turn up a LS digikam image and see
what the deltas are before following up on this bug with specifics. I think
for the most part the LS will work.

I'll try and find some time this weekend to dig into it a bit more.

**Comment by r-pufky** [comment]
I've tested both containers; here are the open issues outside of the localization comment discussed above:

### 1) Import/Export services requiring weblogin hang indefintely.

  A browser installation is required to proxy login and cache credentials. There is not a default browser configured in the ls/digi container currently.

#### Reproduction

  Import: Import -> Import from Smugmug
  Export: Export -> Export to Smugmug

#### Expected Behavior
A browser window is launched to auth to the import/export in question, then returning to digikam to finish the process.

#### Actual Behavior
Digikam hangs indefinitely at the 'Logging in to SmugMug service ...'. See screenshot:
![digikam-import-export-service-login](https://user-images.githubusercontent.com/4778046/156952636-ef7be86f-f264-4320-8878-337f287df8a1.png)

#### Previous resolution
This was resolved in my container by including a long term support firefox browser to proxy login.
See: https://github.com/r-pufky/digikam/issues/12

### 2) Exiftool cannot be loaded.
Exiftool is used to modify additional exif data for images.

#### Reproduction
1. Open an image.
2. Click on 'Metadata' on the right hand expansion tab
3. click on 'exiftool' tab (top right)

#### Expected Behavior
exiftool is run providing for additional exif data manipulation.

#### Actual Behavior
Digikam fails with `execve: No such file or directory`.
![digikam-exiftool-missing](https://user-images.githubusercontent.com/4778046/156952882-7c332349-c106-4ca9-8244-deae2ba8feff.png)

#### Previous resolution
Installing exiftool and ensuring it is in the user's path should resolve this issue.
See: https://github.com/r-pufky/digikam/issues/11


### 3) Closing Digikam window does not auto-restart it.
If the digikam window is closed, it is not auto-relaunched; resulting in a black screen until the container is restarted.

#### Reproduction
1. Start digikam
2. Close digikam

#### Expected Behavior
Digikam automatically restarts.

#### Actual Behavior
Black screen. No action can be taken.

#### Previous resolution
If the process exits, it is restarted.

**Comment by thelamer** [comment]
You can right click the desktop to launch a terminal or digikam. You are inside a full DE (openbox) in our baseimage not a sandbox.
Fire up a terminal and try `sudo pacman -Sy perl-image-exiftool firefox` and see if that resolves it.

As far as auto relaunching that is something we don't do, doesn't really apply here, but people can run multiple windows or close an app if not in use. But we always provide a way to launch the embedded app from the openbox menu. 
Menu here :
https://github.com/linuxserver/docker-digikam/blob/master/root/defaults/menu.xml

Firefox entry example here:
https://github.com/linuxserver/docker-webtop/blob/arch-openbox/root/defaults/menu.xml#L6

Mobile right now, but if installing those two packages works I can PR that in when I get back to a computer, or you can if you want to.

**Comment by r-pufky** [comment]
Confirmed that latest image changes built from repo addresss remaining open issues that can be resolved -- thanks for the changes.

I'm going to push one last update on my image and writing migration instructions to the LS image.

Thanks for the help!
