### ISSUE TITLE
digicam does not start, libicu missing

### ISSUE THREAD

**Issue by daniauri** [linuxserver/docker-digikam#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
DigiKam starts with graphical system.

## Current Behavior
DigiKam does not start, blank desktop when connecting via RDP in webbrowser, terminal and firefox starts using right-klick-menu.
When running digikam in terminal **libicui18n.so.72** is missing.
![image](https://user-images.githubusercontent.com/51371774/200844986-7c3f4e9d-1474-41ac-b019-835c04b2b7e6.png)

## Steps to Reproduce

1. Start docker-compose
2. Open webbrowser on remote machine http://<hostname>:5801/

## Environment
**OS:** Linux 835fef2e06e3 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64
**CPU architecture:** x86_64
**How docker service was installed:** arch comunity repo
community/docker-compose 2.12.2-1 (10.7 MiB 47.0 MiB)
community/docker 1:20.10.21-1 (27.6 MiB 113.5 MiB)

## Command used to create docker container (run/create/compose/screenshot)

_docker-compose.yml_
[...]
  digikam:
    image: lscr.io/linuxserver/digikam:latest
    container_name: digikam
    environment:
      - PUID=1005
      - PGID=1000
      - TZ=Europe/Berlin
      - SUBFOLDER=/ #optional
      - KEYBOARD=de-de-qwertz #optional
    volumes:
      - /var/lib/digikam:/config
      - /home/media/photo:/photo
    ports:
      - 5801:3000
    restart: unless-stopped
[...]

## Docker logs

➜  docker sudo docker-compose up digikam
[+] Running 2/2
 ⠿ Network docker_default  Created                                                                                                                                     0.0s
 ⠿ Container digikam       Created                                                                                                                                     0.5s
Attaching to digikam
digikam  | [custom-init] No custom services found, skipping...
digikam  | [migrations] started
digikam  | [migrations] no migrations found
digikam  |
digikam  | -------------------------------------
digikam  |           _         ()
digikam  |          | |  ___   _    __
digikam  |          | | / __| | |  /  \
digikam  |          | | \__ \ | | | () |
digikam  |          |_| |___/ |_|  \__/
digikam  |
digikam  |
digikam  | Brought to you by linuxserver.io
digikam  | -------------------------------------
digikam  |
digikam  | To support LSIO projects visit:
digikam  | https://www.linuxserver.io/donate/
digikam  | -------------------------------------
digikam  | GID/UID
digikam  | -------------------------------------
digikam  |
digikam  | User uid:    1005
digikam  | User gid:    1000
digikam  | -------------------------------------
digikam  |
digikam  |
digikam  | Generating 2048 bit rsa key...
digikam  |
digikam  | ssl_gen_key_xrdp1 ok
digikam  |
digikam  | saving to rsakeys.ini
digikam  |
digikam  | Generating a RSA private key
digikam  | .............................................................+++++
digikam  | ......+++++
digikam  | writing new private key to '/etc/xrdp/key.pem'
digikam  | -----
digikam  | Changing shell for abc.
digikam  | chsh: Shell not changed.
digikam  | [custom-init] No custom files found, skipping...
digikam  | guacd[195]: INFO:    Guacamole proxy daemon (guacd) version 1.1.0 started
digikam  | guacd[195]: INFO:    Listening on host 0.0.0.0, port 4822
digikam  | guacd[195]: INFO:    Guacamole connection closed during handshake
digikam  | Starting guacamole-lite websocket server
digikam  | listening on *:3000
digikam  | [guac-init] Auto start not set, application start on login
digikam  | [ls.io-init] done.

_Webbrowser connecting to <hostname>:5801_

digikam  | [guac-init] Auto start not set, application start on login
digikam  | [ls.io-init] done.
digikam  | [2022-11-09 14:48:07] [Connection 1]  Client connection open
digikam  | [2022-11-09 14:48:07] [Connection 1]  Opening guacd connection
digikam  | [2022-11-09 14:48:07] [Connection 1]  guacd connection open
digikam  | [2022-11-09 14:48:07] [Connection 1]  Selecting connection type: rdp
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 6.select,3.rdp;
digikam  | guacd[195]: INFO:    Creating new client for protocol "rdp"
digikam  | guacd[195]: INFO:    Connection ID is "$6e77dfa5-7e01-460a-8202-e882d708385d"
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 4.size,4.2560,14.1297?undefined,2.96;
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 5.video;
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 5.image;
digikam  | [2022-11-09 14:48:07] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,
13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,2
1.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16
.gateway-password,17.load-balance-info
digikam  | [2022-11-09 14:48:07] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.2560,14.1297?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,12.de-de-qwertz,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
digikam  | guacd[251]: INFO:    Security mode: Negotiate (ANY)
digikam  | guacd[251]: INFO:    Resize method: none
digikam  | guacd[251]: INFO:    User "@e1df9b73-732c-4584-8e67-7fa129c0336b" joined connection "$6e77dfa5-7e01-460a-8202-e882d708385d" (1 users now present)
digikam  | guacd[251]: INFO:    Loading keymap "base"
digikam  | guacd[251]: INFO:    Loading keymap "de-de-qwertz"
digikam  | sh: line 1: xauth: command not found
digikam  |
digikam  | X.Org X Server 1.21.1.4
digikam  | X Protocol Version 11, Revision 0
digikam  | Current Operating System: Linux 835fef2e06e3 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64
digikam  | Kernel command line: initrd=\intel-ucode.img initrd=\initramfs-linux.img rd.luks.name=<Name>=cryptroot root=/dev/mapper/cryptroot rw quiet splash plymouth.ignore-serial-consoles audit=0 delayacct
digikam  |
digikam  | Current version of pixman: 0.40.0
digikam  |      Before reporting problems, check http://wiki.x.org
digikam  |      to make sure that you have the latest version.
digikam  | Markers: (--) probed, (**) from config file, (==) default setting,
digikam  |      (++) from command line, (!!) notice, (II) informational,
digikam  |      (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
digikam  | (++) Log file: ".xorgxrdp.10.log", Time: Wed Nov  9 13:48:08 2022
digikam  | (++) Using config file: "/etc/X11/xrdp/xorg.conf"
digikam  | (==) Using system config directory "/usr/share/X11/xorg.conf.d"
digikam  | xorgxrdpSetup:
digikam  | xrdpdevSetup:
digikam  | rdpmousePlug:
digikam  | rdpkeybPlug:
digikam  | rdpIdentify:
digikam  | rdpDriverFunc: op 10
digikam  | rdpProbe:
digikam  | rdpPreInit:
digikam  | rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
digikam  | rdpScreenInit: pfbMemory bytes 1920000
digikam  | rdpScreenInit: pfbMemory 0x7fa1600ff010
digikam  | rdpSimdInit: assigning yuv functions
digikam  | rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000806e9 bx 0x03100800 cx 0x7ffafbbf dx 0xbfebfbff
digikam  | rdpSimdInit: sse2 amd64 yuv functions assigned
digikam  | rdpClientConInit: disconnect idle session after [0] sec
digikam  | rdpClientConInit: kill disconnected [0] timeout [0] sec
digikam  | rdpClientConInit: do_touchpad_scroll_hack [0]
digikam  | rdpXvInit: depth 24
digikam  | rdpScreenInit: out
digikam  | rdpCreateScreenResources:
digikam  | fuse: device not found, try 'modprobe fuse' first
digikam  | rdpmousePreInit: drv 0x563208362370 info 0x563208621af0, flags 0x0
digikam  | rdpmouseControl: what 0
digikam  | rdpmouseDeviceInit:
digikam  | rdpmouseCtrl:
digikam  | rdpRegisterInputCallback: type 1 proc 0x7fa16154f2c0
digikam  | rdpmouseControl: what 1
digikam  | rdpmouseDeviceOn:
digikam  | rdpkeybPreInit: drv 0x563208361d20 info 0x563208624c40, flags 0x0
digikam  | rdpkeybControl: what 0
digikam  | rdpkeybDeviceInit:
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat on
digikam  | rdpRegisterInputCallback: type 0 proc 0x7fa16154a920
digikam  | rdpkeybControl: what 1
digikam  | rdpkeybDeviceOn:
digikam  | rdpDeferredRandR:
digikam  | rdpResizeSession: width 1024 height 768
digikam  |   calling RRScreenSizeSet
digikam  | rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
digikam  | rdpRRGetInfo:
digikam  |   screen resized to 1024x768
digikam  |   RRScreenSizeSet ok 1
digikam  | rdpResizeSession: width 2560 height 1297
digikam  |   calling RRScreenSizeSet
digikam  | rdpRRScreenSetSize: width 2560 height 1297 mmWidth 677 mmHeight 343
digikam  | rdpRRGetInfo:
digikam  |   screen resized to 2560x1297
digikam  |   RRScreenSizeSet ok 1
digikam  | rdpClientConGotConnection:
digikam  | rdpClientConGotConnection: g_sck_accept ok new_sck 9
digikam  | rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
digikam  | rdpAddClientConToDev: adding first clientCon 0x56320864b3d0
digikam  | rdpClientConProcessMsgVersion: version 0 0 0 1
digikam  | rdpClientConProcessScreenSizeMsg: set width 2560 height 1297 bpp 16
digikam  | rdpClientConAllocateSharedMemory: shmemid 0 shmemptr 0x7fa1543a4000 bytes 6640640
digikam  | rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 2560 cy 1297
digikam  | rdpClientConProcessMsgClientInfo:
digikam  |   got client info bytes 7072
digikam  |   jpeg support 0
digikam  |   offscreen support 0
digikam  |   offscreen size 0
digikam  |   offscreen entries 0
digikam  |   client supports glyph cache but server disabled
digikam  |   client can not do offscreen to offscreen blits
digikam  |   client can do new(color) cursor
digikam  |   client can not do multimon
digikam  | rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
digikam  | rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 2560 height 1297
digikam  | rdpLoadLayout: keylayout 0x00000407 variant  display 10
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat on
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat on
digikam  | (EE) Failed to open authorization file ".Xauthority": No such file or directory
digikam  | fuse: device not found, try 'modprobe fuse' first
digikam  | fuse: device not found, try 'modprobe fuse' first
digikam  | rdpInDeferredRepeatCallback:
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat off
digikam  | rdpInDeferredRepeatCallback:
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat off
digikam  | rdpInDeferredRepeatCallback:
digikam  | rdpkeybChangeKeyboardControl:
digikam  | rdpkeybChangeKeyboardControl: autoRepeat off
digikam  | guacd[251]: INFO:    Accepted format: 16-bit PCM with 2 channels at 44100 Hz
digikam  | guacd[251]: INFO:    Accepted format: 16-bit PCM with 2 channels at 22050 Hz
digikam  | guacd[251]: INFO:    Connected to RDPDR 1.12 as client 0x3ccfa279
digikam  | guacd[251]: INFO:    RDPDR user logged on

**Comment by sespiros** [comment]
@daniauri It seems like the image is not up-to-date. I managed to fix this with this workaround:
```
sudo pacman -Syy
sudo pacman -Syu
```

**Comment by jwhdoges** [comment]
I had the same problem, thanks for the workaround.

**Comment by daniauri** [comment]
Yes, this works for me too. Big Thanks.
Strange though, I always pull an update with 
docker-compose update
and thought this also pulls the compatible Linux system image.

How to make sure I get the right image next time?

Should I close the issue?

**Comment by thespad** [comment]
It's an issue with how Arch handles packages.

If a dep gets updated somewhere it needs every image in our baseimage chain to be rebuilt in order for the deps to be correct. Running a `pacman -Syu` on build would massively bloat the resultant images but hundreds of Mb.

I'm in the process of pushing everything through the pipeline but it'll probably be tomorrow before it's working OOTB again.

**Comment by daniauri** [comment]
Thank you for the clarification.

**Comment by sespiros** [comment]
Also note that with the "workaround" I get other issues when rebooting such as:
```
/usr/sbin/xrdp-sesman: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
that are caused because the openssl gets upgraded to version 3 while packages such as xrdp use the old one. It seems that xrdp is not pulled as part of the update.

**Comment by andreascschmidt** [comment]
I don't want to start a flame or blame war, but I recently switched to https://github.com/r-pufky/digikam since that runs subjective faster and with fewer issues lately. Maybe worth to look into.

**Comment by thespad** [comment]
This morning's build should have resolved the ICU issue
