### ISSUE TITLE
[BUG] Version 2022-12-23-ls115 not works

### ISSUE THREAD

**Issue by piotrminkina** [linuxserver/docker-digikam#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DigiKam not works in version _2022-12-23-ls115_. I also tested version _2022-12-16-ls114_ and this version works like a charm.

Version _2022-12-16-ls114_:
![Screenshot from 2022-12-28 21-19-12](https://user-images.githubusercontent.com/2574153/209868515-11fe9221-1b40-4481-85ea-1eb7dac2c490.png)

Version _2022-12-23-ls115_:
![Screenshot from 2022-12-28 21-20-21](https://user-images.githubusercontent.com/2574153/209868551-2578df98-d1c6-45d4-b0eb-3ceea257b650.png)
![Screenshot from 2022-12-28 21-24-29](https://user-images.githubusercontent.com/2574153/209868557-abb288ce-01d1-4180-aa89-4d22d801e026.png)

### Expected Behavior

Should works, like version _2022-12-16-ls114_ ;)

### Steps To Reproduce

1. Simply run DigiKam via Docker.
2. Try to open in browser.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: `docker-ce` package from repo `https://download.docker.com/linux/ubuntu` via `apt install`
```

### CPU architecture

x86-64

### Docker creation

1. docker run --rm -it -p 3000:3000 lscr.io/linuxserver/digikam:2022-12-16-ls114
2. docker run --rm -it -p 3000:3000 lscr.io/linuxserver/digikam:2022-12-23-ls115

### Container logs

1. [2022-12-16-ls114.txt](https://github.com/linuxserver/docker-digikam/files/10316283/2022-12-16-ls114.txt)
2. [2022-12-23-ls115.txt](https://github.com/linuxserver/docker-digikam/files/10316284/2022-12-23-ls115.txt)

**Comment by thespad** [comment]
Could be an arch dependency issue, sometimes the deps change out of sync and we have to wait for the baseimages to catch up before the builds will work again.

I would suggest pinning to ls114 and then try the next build of digikam we publish. If it's still broken then, we'll look into it in more detail.

**Comment by piotrminkina** [comment]
@thespad OK :)

**Comment by piotrminkina** [comment]
Version _2022-12-30-ls116_ also not works. I checked that problem exists in _linuxserver/baseimage-rdesktop-web:arch_ image, since version _arch-2022-12-23-ls73_.

**Comment by thespad** [comment]
OK, I'll have a look tomorrow and see if I can figure out where things have broken.

**Comment by thespad** [comment]
Should be fixed by https://github.com/linuxserver/docker-baseimage-rdesktop/pull/47 once it's merged and the changes have had time to flow down this image.

**Comment by thespad** [comment]
@piotrminkina please test the latest build and see if you're still seeing issues.

**Comment by piotrminkina** [comment]
@thespad Version _2023-01-02-ls117_ is operational. DigiKam is starting up. Thanks for your work!
