### ISSUE TITLE
[FEAT] Update to 8.1.0

### ISSUE THREAD

**Issue by totti4ever** [linuxserver/docker-digikam#38]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

8.0 has been released in April, 8.1 in July - any chance to see the latest version in the container, soon?

cheers and klind regards!

### Reason for change

update / changelog

**Comment by thelamer** [comment]
That is my fault, when I rebased this repo I forgot to update the ingestion trigger. All build now: 
https://ci-tests.linuxserver.io/linuxserver/digikam/a015c45a-ls140/index.html

**Comment by totti4ever** [comment]
yeah, nice - thanks a lot!
