### ISSUE TITLE
[BUG] Version date from 7.8

### ISSUE THREAD

**Issue by webysther** [linuxserver/docker-digikam#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The version use date and is new in every ls* build from >7.8.

### Expected Behavior

Use the same version from digikam (today is 8.1.*) and maybe use either major tag like v8 or v8.1 for be possible to get the new release without change the docker compose with safety.

### Steps To Reproduce

.

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by Roxedus** [comment]
This is unfortunately not feasible, due to how the time-dependent the baseimage is. It requires us to build it pretty often(regardless of application  updates), so that the Arch keychain is not outdated.
