### ISSUE TITLE
[BUG] Segmentation fault and black screen when updating to ls224

### ISSUE THREAD

**Issue by kso512** [linuxserver/docker-digikam#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting a container that worked in the last version, I get a black screen via the KASM portal.  I can right-click on the black screen and run XTerm and Firefox.  When running digiKam via XTerm, it immediately dumps a core because of segmentation fault.

I also verified this on multiple machines and with a clean install.

This does not appear related to issue #36 as the docker logs are different.

Comparing the [most recent CI results](https://ci-tests.linuxserver.io/linuxserver/digikam/2024-11-22-ls224/index.html) with the [previous version](https://ci-tests.linuxserver.io/linuxserver/digikam/2024-11-15-ls223/index.html) shows the same thing.  Last time, we see a Welcome to digiKam screen; now we see black.

### Expected Behavior

Digikam should auto start and not segmentation fault.  It should also run via XTerm, not segfault there either.

### Steps To Reproduce

1. Follow installation instructions
2. See blank screen

### Environment

```markdown
- OS: Debian bullseye & testing
- How docker service was installed: per Docker instructions; other containers running fine
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run ghcr.io/linuxserver/digikam:version-2024-11-22
```

### Container logs

```bash
Unable to find image 'ghcr.io/linuxserver/digikam:version-2024-11-22' locally
version-2024-11-22: Pulling from linuxserver/digikam
Digest: sha256:4934dc38d7353e75dda895dc952a1caf6aa88934a12f4eebfe2d384b7186b942
Status: Downloaded newer image for ghcr.io/linuxserver/digikam:version-2024-11-22
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
....+...+..+...+++++++++++++++++++++++++++++++++++++++*.+++++++++++++++++++++++++++++++++++++++*......+..+....+...+...+.........+.........+.........+...+..............+..................+.+..+...+..........+......+....................+.+.......................+.....................+...+.+......+......+..+.+...........+..........+........+.......+...+...+..+...+...+..........+..+...+..........+.........+...............+.....+.+..+...+....+.....+...............+.+............+..............+......+...............+..................+.......+........+....+...+.......................+.+...+..+......+...+............+...+....+.....+.+......+...+.....+...+............+.+............+..............+...+.+.....+....+..+.+..+.......+.....+.+............+........+.........+....+..+..........+.................+.+..............+.+.....+.+.....+......+.........+................+...+..+.......+..+.........+.......+.........+.....+.+...............+..+...+...+......++++++
..+.............+.....+.+...+.....+......+............+...+....+...+.....+...+.+...+...+...............+...+..+.........+..........+...+...+..+.+..+...+......+.+..+.+......+.........+...........+...+...+++++++++++++++++++++++++++++++++++++++*.+..+...+.+......+........+.......+.....+....+...+..+...+...+..........+........+....+..+....+..+....+.....+......+..........+...+++++++++++++++++++++++++++++++++++++++*.......+..............+.........+....+...+..+......+................+........+...+.......+..+................+...+.....+......+......+.........................+...+..+.........+.+...+...........+.+..+.+..+..........+..+......+....+...+.....+...................+...+.....+.+.....+.........+...+...+.+....................+.........+....+...+.........+.....+.+...+.....+......+..........+...+..................+............+.....+......+.+......+...+......+...+..+......+...+....+..+......+............+.+..+............+.......+...+.....+.+..+.........+................+........+.+...+..+.........+....+......+.....+....+..+.+..+...+....+.........+.........+...+...+......+...+......+.....+.......++++++
-----
[custom-init] No custom files found, skipping...
which: no nvidia-smi in (/command:/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
2024/11/23 22:16:20 [warn] 201#201: could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.3.3 - built Nov 22 2024 16:28:07
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
19
/config/.config/openbox/autostart: line 1:   260 Segmentation fault      (core dumped) digikam
```

**Comment by kso512** [comment]
I was able to get back online by reverting to the previous version.

**Comment by aptalca** [comment]
It looks like an issue with the latest version, likely an arch issue as we install from the arch repo.

**Comment by thelamer** [comment]
Yeah it is busted at head, will dig in tomorrow.

**Comment by thelamer** [comment]
Did not have time today, but did run some basic tests to see if it is sandboxing. Might need to rebase to Debian and drop aarch64 support for now, will know more tomorrow.

**Comment by thelamer** [comment]
People in this thread please try the `ghcr.io/linuxserver/lsiodev-digikam:8.5.0-debian-rebase` tag and let me know if the transition from arch to debian is smooth. The only question mark is if the mariadb binaries got switched around at all. Internal testing with a simple database worked both sqlite and mariadb internal. 

This rebases to debian and uses the official appimage to install digikam

MR ref: 
https://github.com/linuxserver/docker-digikam/pull/47

Testing ref: 
https://ci-tests.linuxserver.io/lsiodev/digikam/8.5.0-pkg-f8f4c0e7-dev-3a71a6a3da452e039c53b016e15c209dec75a745/index.html

**Comment by kso512** [comment]
Thank you @thelamer 

I also got a black screen when testing with "ghcr.io/linuxserver/lsiodev-digikam:8.5.0-debian-rebase"

When I right-click and select DigiKam from the menu, this error appears:

> Openbox
> Failed to execute child process "/usr/sbin/digikam" (No such file or directory)

I was able to right-click and open xterm.  `command -v digikam` returns nothing.

Digging around a bit, I see some `digikam` folders under opt:

```
root@11445c4c967e:/# find /opt -name digikam
/opt/digikam
/opt/digikam/usr/share/digikam
/opt/digikam/usr/share/kxmlgui5/digikam
/opt/digikam/usr/bin/digikam
/opt/digikam/usr/plugins/digikam
```

However, when I try to run the binary, it fails with this error:

```
root@11445c4c967e:/# /opt/digikam/usr/bin/digikam 
/opt/digikam/usr/bin/digikam: error while loading shared libraries: libdigikamgui.so.8.5.0: cannot open shared object file: No such file or directory
```

**Comment by thelamer** [comment]
Ok the problem is your `/config/.config/openbox/autostart` file and the menu.xml files are pointed to the old bin locations, you can delete them to test, but I will make symlinks in the new image for compatibility.

**Comment by kso512** [comment]
I removed `/config/.config/openbox/autostart` and re-deployed the container.

I saw "A MySQL database upgrade is in progress, please wait..." for about 2 minutes, then the following error appeared:

![Screenshot_20241125_175827](https://github.com/user-attachments/assets/de89c10b-a5ab-4663-8e3a-3d85faa744c9)

**Comment by thelamer** [comment]
> I removed `/config/.config/openbox/autostart` and re-deployed the container.
> 
> I saw "A MySQL database upgrade is in progress, please wait..." for about 2 minutes, then the following error appeared:
> 
> ![Screenshot_20241125_175827](https://private-user-images.githubusercontent.com/8507799/389646249-de89c10b-a5ab-4663-8e3a-3d85faa744c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTgyNTIsIm5iZiI6MTczMjU1Nzk1MiwicGF0aCI6Ii84NTA3Nzk5LzM4OTY0NjI0OS1kZTg5YzEwYi1hNWFiLTQ2NjMtOGUzYS0zZDg1ZmFhNzQ0YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTgwNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM4MjdmZmE2M2Y5NWRhMDc5NGUyYjJmYzgwN2M4NTNiYmNhZjE5ODk3MDhhNmI5ZGZjNjM3ZmI3MmM3ODg0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4FT1HEhSYk9aoiNBP7i-lTW3JfE1Xv5R7bli5HLbezU)

So this looks to be unavoidable, restarting the internal mariadb server inside the container does not work properly, but just restarting the container or launching it a couple times will get it back up. 
This looks like it will happen with any database schema upgrade when using mysql internal and is a side effect of going to 8.5.0 and not the rebase or a change in their binaries for the database.

**Comment by thelamer** [comment]
I have updated with changes and dropped aarch64 support. Will leave this issue open for now with history and for people running into issues.

**Comment by kso512** [comment]
> I have updated with changes and dropped aarch64 support. Will leave this issue open for now with history and for people running into issues.
> 
> For people that want a full upgrade run:
> 
> ```
> rm -f /config/.config/openbox/autostart /config/.config/openbox/menu.xml
> ```
> 
> And restart the container, I created symlinks for compatibility, but the desktop menu will be missing icons and such without this.

This worked for my existing deployment, and all my pictures are still there.

Thanks all!
