### ISSUE TITLE
Video stuttering and no audio

### ISSUE THREAD

**Issue by AlmightyFrog** [linuxserver/docker-digikam#9]
Idea of running digikam remotely accessible via guacamole and directly RDP is nice and works perfectly for photos, but with videos i have a big issue:
Using digikam also for videos is not possible: The video is stuttering and i have no audio at all.
Searched a little around in internet but didn't find any good solution or alternative. Guess stuttering of video is something you have to live with, but audio should work.

To check if it is only digikam and/or local video playback, i also installed for test mplayer and firefox in the container.
Both mplayer for local files and firefox for youtube did provide video with only minimal stuttering and also audio.
So i guess issue is within digikam.

Not sure, but i have feeling that removing the preselected "Disable hardware acceleration OpenCL" which you can find in "Configure digiKam" > "Miscellaneous" > "System" solves the video stuttering issue.

But still no audio. Installing pavucontrol I can see there is Playback audio stream available for digikam and it is showing also some different "volumes" (not sure what correct term for this is, the peaking blue bar how lowd it currently is) which are also showing up at output devices in "xrdp sink".
If you play video e.g. in firefox, there is also then a playback device and the volume displays there and in output devices; but difference to digikam is, there i can hear it.
Any idea what causes this - is this maybe an issue with digicam running as appimage? I read some that people have problems getting audio out with it, but as it show up as pulseadio playback not sure if that is same issue.

------------------------------

## Expected Behavior
Video with less (or without? :) ) stuttering. audio plays.

## Current Behavior
Video is stuttering, no audio.

## Steps to Reproduce
1. Play back any video file from your digikam

**Comment by thelamer** [comment]
@AlmightyFrog I just rebased this image to arch to stop using the appimage and support Arm. 
I have a pending tweak for more reliable audio startup that might not build through until tomorrow: 
https://github.com/linuxserver/docker-baseimage-rdesktop-web/blob/8c9b93144305391d5c81204a6f1aace1468f7c54/root/defaults/startwm.sh#L4

But in general this is pretty usable from my side, there is slight tearing, but that is just the RDP protocol. 


https://user-images.githubusercontent.com/1852688/154371299-3eef8a2d-3107-4ea8-8e5c-06eb15e7d354.mp4
